import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import { useState } from "react";
import Modal from "@component/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [modalClicked, setModalClicked] = useState(false);

  const handleModalClick = () => {
    setModalClicked(true);
  };

  return (
    <>
      <Head>
        <title>Modal with animation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => handleModalClick()}
          className={styles.main__modalButton}
        >
          Open Modal
        </button>
      </main>
      <Modal modalClicked={modalClicked} setModalClicked={setModalClicked} />
    </>
  );
}
